### ISSUE TITLE
No withdrawal email received.

### ISSUE THREAD

**Issue by jamesbourne777** [hitbtc-com/hitbtc-api#177]
Having tried to withdraw ERC20 tokens for the last 10 days, so far without success, I am of the opinion that @hitbtc-com either does not have the tokens, or has switched off the withdrawal email verification. 

I've received emails from them in the past, and have no issues with any other exchange.

Their telegram link goes nowhere, same with facebook & twitter.

Support reply, but appears to be delaying tactics.

Exit scam?

I know that QSP audited ERC20 tokens for binance, and found no issues, so @hitbtc-com -what's going on?

**Comment by hitbtc-com** [comment]
Dear @jamesbourne777,
The thing is, that's most likely to be due to the fact that one of our sender services cannot reach your email provider - you can either contact your email provider or try to request an email once again.
We are terribly sorry for the inconvenience and hope things go well with you! Let us know if the issue still persists.
