### ISSUE TITLE
Affiliate System Not Working

### ISSUE THREAD

**Issue by primski** [hitbtc-com/hitbtc-api#192]
I know I have some registered users, but reports show nothing

will these users count or should i just find new friends?

**Comment by hitbtc-com** [comment]
Dear @primski,
Even though an affiliate program is being updated at the current moment, the users you attract now are still counted.

**Comment by Luckygerman** [comment]
Hello @hitbtc-com ,

Maybe you should consider to fix the program? Because a lot of people have put effort in your company and you don't give a f*ck about them. You earned a lot of fee's and you are not willing to give them back what is agreed? Maybe give us for once a fair answer with a specific date!

Regards

**Comment by Luckygerman** [comment]
Isnt solved yet

Verstuurd vanaf mijn iPhone
