### ISSUE TITLE
HitBTC are bandits, scam

### ISSUE THREAD

**Issue by quyenbnvn** [hitbtc-com/hitbtc-api#217]
HitBTC are bandits, scam

**Comment by quyenbnvn** [comment]
HitBTC are bandits, scam

**Comment by quyenbnvn** [comment]
HitBTC are bandits, scam

**Comment by quyenbnvn** [comment]
HitBTC are bandits, scam

**Comment by quyenbnvn** [comment]
HitBTC are bandits, scam

**Comment by ytrezq** [comment]
@hitbtc-com : hi, while not going as far this, I would have a question about a problem in support :

When my tickets are assigned to her, she takes a months to a full year to reply. My withdrawals got disabled a week ago, I created a ticket and it was solved in 5 hours (because it got assigned to someone else). And now it’s disabled again : I created the same type of tickets but as it was assigned to Jane Park again and didn’t received any initial responses for 3 days.

How to no longer get my tickets not assigned to her or report it’s behavior? (if I ask the question in support then the  ticket is almost all of the time assigned to here which makes it is left unswared for months).
